/* Lógico_1: */

CREATE DATABASE EXERCICIO_DORNELFALTOU3

USE EXERCICIO_DORNELFALTOU3

-- DROP TABLE [MULTIPLICADOR]

CREATE TABLE COLABORADOR (
    CPF NUMERIC,
    MATRICULACOLAB NUMERIC PRIMARY KEY,
    AREA CHAR(50),
    NOME CHAR(50)
);

CREATE TABLE MULTIPLICADOR (
    TREINAMENTO CHAR(50),
    NOMEMULT CHAR(50),
    MATRICULAMULTI NUMERIC PRIMARY KEY,
);

CREATE TABLE RH (
    FK_RH_MATRICULACOLAB NUMERIC,
    FK_RH_TREINAMENTO CHAR(50),
    FK_MULTIPLICADOR_MATRICULAMULTI NUMERIC,
);

INSERT MULTIPLICADOR (TREINAMENTO,NOMEMULT,MATRICULAMULTI)
VALUES ('NR11','MARCELINDO',5115926)

SELECT * FROM COLABORADOR
SELECT * FROM MULTIPLICADOR
SELECT * FROM RH