CREATE TABLE FUNCIONARIO(
    FUNCOD INT PRIMARY KEY,
    FUNNOME CHAR(10)
)
INSERT FUNCIONARIO (FUNCOD, FUNNOME) VALUES (1,'DORNEL')

CREATE TABLE DEPENDENTES(
    DEPCOD INT PRIMARY KEY,
    DEPNOME CHAR(10),
    FUNCOD INT
    CONSTRAINT FK_FUN_DEP FOREIGN KEY (FUNCOD)
    REFERENCES FUNCIONARIO (FUNCOD)
)

INSERT DEPENDENTES (DEPCOD,DEPNOME,FUNCOD) VALUES (1,'LUÍSA',1)

DELETE FROM FUNCIONARIO WHERE FUNCOD = 1 -- NÃO FUNCIONA PORQUE FOI EMPRESTADO O FUNCOD PRO DEPENDENTE
DELETE FROM DEPENDENTES WHERE FUNCOD = 1 -- DELETAR PRIMEIRO O DEPENDENTE
DELETE FROM FUNCIONARIO WHERE FUNCOD = 1 -- DELETAR O FUNCIONARIO





SELECT * FROM FUNCIONARIO
SELECT * FROM DEPENDENTES